---
services:
  app:
    image: ghcr.io/skrtheg/dump-truck-sensor-monitoring:latest
    container_name: app
    ports:
      - "8501:8501"  # Main Dashboard
      - "8502:8502"  # Braking System
      - "8503:8503"  # Engine System
      - "8504:8504"  # Tire System
      - "8505:8505"  # Vibration Analysis
    environment:
      - PYTHONUNBUFFERED=1
    env_file:
      - .env
    restart: unless-stopped
    labels:
      - "com.centurylinklabs.watchtower.enable=true"

  watchtower:
    image: containrrr/watchtower:latest
    container_name: watchtower
    restart: unless-stopped
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    command: --interval 3600 --cleanup --stop-timeout 60s app